name: C/C++ CI

on: [push, pull_request]

jobs:
  linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build-linux-editor-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons platform=linux target=editor generate_bindings=yes -j $(nproc)
          ldd demo/addons/godot-git-plugin/linux/*.so
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.linux.x86_64.editor.so-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  windows-x64:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"
      - uses: ilammy/msvc-dev-cmd@v1
      - name: build-windows-editor-x64
        run: |
          git submodule update --init --recursive
          pip3 install --user scons
          scons platform=windows target=editor generate_bindings=yes -j $env:NUMBER_OF_PROCESSORS
          dumpbin /dependents .\demo\addons\godot-git-plugin\win64\*.dll
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.windows.x86_64.editor.dll-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/

  macos-universal:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - name: build-macos-editor-universal
        run: |
          git submodule update --init --recursive
          brew install scons
          scons platform=macos target=editor generate_bindings=yes macos_arch=universal use_llvm=yes macos_deployment_target=10.13 -j $(sysctl -n hw.logicalcpu)
          otool -L demo/addons/godot-git-plugin/macos/*.dylib
      - uses: actions/upload-artifact@v2
        with:
          name: libgit_plugin.macos.universal.editor.dylib-${{ github.sha }}
          if-no-files-found: error
          path: |
            demo/
